version: "2"

linters:
  default: standard
  enable:
    - asciicheck
    - bidichk
    - dogsled
    - dupword
    - errname
    - godot
    - impoirtas
    - misspell
    - modernize
    - nilerr
    - nilnesser
    - noctx
    - nolintlint
    - prealloc
    - recvcheck
    - revive
    - sloglint
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - whitespace

  exclusions:
    generated: lax
    presets:
      - std-error-handling

  settings:
    revive:
      confidence: 0.8
      severity: error
      enable-default-rules: true
      rules:
        - name: atomic
        - name: deep-exit
        - name: defer
        - name: if-return
        - name: unnecessary-stmt
        - name: unused-receiver
        - name: use-any
        - name: useless-break
        - name: waitgroup-by-value

    nolintlint:
      require-explanation: true
      require-specific: true

formatters:
  enable:
    - golines
    - gci
    - gofumpt

  settings:
    golines:
      max-len: 100

    gofumpt:
      extra-rules: true

    gci:
      sections:
        - standard
        - default
        - localmodule
