name: "Go: Cache Warmup"
on:
  workflow_call: {}

jobs:
  build:
    name: Cache Warmup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          cache: false
          go-version-file: go.mod


      - id: go-cache-paths
        run: |
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
          mkdir -p "$(go env GOMODCACHE)"

      - id: cache-lookup
        uses: actions/cache/restore@v6
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
          lookup-only: true

      - if: ${{ steps.cache-lookup.outputs.cache-hit != 'true' }}
        run: |
          go mod download
      - if: ${{ steps.cache-lookup.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v6
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
