name: "Go: Release"
on:
  workflow_call: {}
  workflow_dispatch: {}
  push:
    tags:
      # Release workflow tags and drafts the reelase.
      # This workflow fills builds artifacts and publishes the release
      - v*

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-tags: true

      - uses: actions/setup-go@v7
        with:
          cache: false
          go-version-file: go.mod

      - id: go-cache-paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

          mkdir -p "$(go env GOMODCACHE)"
          mkdir -p "$(go env GOCACHE)"

      - name: Go Build Cache
        uses: actions/cache@v6
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-gobuild-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gobuild-build-

      - name: Go Mod Cache
        uses: actions/cache/restore@v6
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-

      - name: Build
        uses: goreleaser/goreleaser-action@v7
        with:
          args: release --clean --snapshot
