name: "Go: Test"
on:
  workflow_call: {}

permissions:
  contents: read
  code-quality: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          cache: false
          go-version-file: go.mod

      - name: Determine Go Cache Paths
        id: go-cache-paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

          mkdir -p "$(go env GOMODCACHE)"
          mkdir -p "$(go env GOCACHE)"

      - name: Go Build Cache
        uses: actions/cache@v6
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-gobuild-test-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gobuild-test

      - name: Go Mod Cache
        uses: actions/cache/restore@v6
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-

      - run: |
          go test -v \
            -coverprofile=coverage.txt \
            -covermode=atomic \
            -coverpkg=./... \
            ./...

      - run: |
          go run github.com/t-yuki/gocover-cobertura@latest \
            < coverage.txt \
            > coverage.xml \
            || exit 0

      - name: Upload coverage report
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@v1
        with:
          file: coverage.xml
          language: Go
          label: code-coverage/go

