name: Release
run-name: Process Release on ${{ github.event.workflow_run.head_branch }} `${{ github.event.workflow_run.head_sha }}`

on:
  workflow_run:
    workflows: ["Go"]
    branches: [main]
    types:
      - completed

concurrency:
  group: release-please-${{ github.ref }}

permissions:
  contents: read


jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v7
      - uses: googleapis/release-please-action@v5

  fail-release:
    name: Fail Release
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'failure'

    permissions: {}

    steps:
      - run: |
          echo "::error ::Cannot release unless 'Go' workflow suceeds!"
          exit 1

  go-release:
    name: "Go: Release"
    needs: release-please
    if: needs.release-please.outputs.releases_created == 'true'

    permissions:
      contents: write

    uses: ./.github/workflows/go-release.yaml
